<?php

return array (
  'version' => '6.0.3',
  'title' => 'Attractions',
  'type' => 'attractions',
  'id' => '63c8b6d61b8f8',
  'updated' => 1676772317,
  'columns' => 
  array (
    '63c8c50a7126e8' => 
    array (
      'type' => 'column-featured_image',
      'label' => 'Image',
      'width' => '130',
      'width_unit' => 'px',
      'featured_image_display' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '110',
      'image_size_h' => '60',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c50a7126e8',
    ),
    '63c8c8717a5e34' => 
    array (
      'type' => 'column-meta',
      'label' => 'Marker',
      'width' => '46',
      'width_unit' => 'px',
      'field' => 'na_attractions_marker',
      'field_type' => 'image',
      'image_size' => 'cpac-custom',
      'image_size_w' => '36',
      'image_size_h' => '',
      'media_link_to' => '',
      'number_of_items' => '10',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c8717a5e34',
    ),
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '300',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '63c8c4a78c49bc' => 
    array (
      'type' => 'column-meta',
      'label' => 'Address',
      'width' => '250',
      'width_unit' => 'px',
      'field' => 'na_attractions_address',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c4a78c49bc',
    ),
    '63c8c4e9fa1cac' => 
    array (
      'type' => 'column-meta',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'na_attractions_description',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c4e9fa1cac',
    ),
    '63c8c4b948f5c4' => 
    array (
      'type' => 'column-meta',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'na_latitude',
      'field_type' => 'numeric',
      'number_format' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c4b948f5c4',
    ),
    '63c8c4c46f9db4' => 
    array (
      'type' => 'column-meta',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'na_longitude',
      'field_type' => 'numeric',
      'number_format' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c4c46f9db4',
    ),
    '63c995eee45a1c' => 
    array (
      'type' => 'column-taxonomy',
      'label' => 'Attraction types',
      'width' => '',
      'width_unit' => '%',
      'taxonomy' => 'attractiontypes',
      'term_link_to' => 'filter',
      'number_of_items' => '10',
      'separator' => 'comma',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c995eee45a1c',
    ),
    '63deceffcf9db4' => 
    array (
      'type' => 'column-meta',
      'label' => 'URL',
      'width' => '',
      'width_unit' => '%',
      'field' => 'na_attractions_url',
      'field_type' => '',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'editable_type' => 'text',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63deceffcf9db4',
    ),
    '63df0a6072f1a8' => 
    array (
      'type' => 'column-meta',
      'label' => 'Always show',
      'width' => '',
      'width_unit' => '%',
      'field' => 'na_attractions_always_show',
      'field_type' => 'checkmark',
      'before' => '',
      'after' => '',
      'edit' => 'on',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63df0a6072f1a8',
    ),
    '63c8c5065fbe78' => 
    array (
      'type' => 'column-status',
      'label' => 'Status',
      'width' => '',
      'width_unit' => '%',
      'use_icon' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63c8c5065fbe78',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_filters' => 'on',
    'hide_filter_post_date' => 'on',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'on',
    'sorting' => '0',
    'sorting_order' => 'asc',
    'primary_column' => '',
  ),
);